# Generated by Django 5.2.2 on 2025-06-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contact',
            new_name='phone',
        ),
    ]
