# Generated by Django 5.2.2 on 2025-06-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_rename_contact_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
